[package]
name = "ff_utils"
version = "1.0.0"
edition = "2021"

[dependencies]
ff = { version = "0.11.0", features = ["default", "derive"] }
group = "0.10"
pairing_ce = "0.24.2"
subtle = "2.4"
byteorder = "1"
bitvec = "0.22"
rand_core = "0.6"
num = "0.4"
hex = "0.4.3"
serde = { version = "^1.0.101", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
num_cpus = "1"
crossbeam = "0.7"

[lib]
name = "ff_utils"
